### ISSUE TITLE
sapfluxnetr Road Map

### ISSUE THREAD

**Issue by MalditoBarbudo** [sapfluxnet/sapfluxnetr#2]
Road map for `sapfluxnetr` package

- [x] Classes definitions
    + [x] single sfn_data
    + [x] multi sfn_data

- [x] Methods definitions
    + [x] ~~join~~ not needed as we have sfn_data_multi constructor
    + [x] get
    + [x] set
    + [x] show
    + [x] validity
    + [x] ~~summary (for multi)~~ not needed as we have the show already
    + [x] plot (done, but not as method, but as a proper function (`sfn_plot`)
    + [x] subset and convert methods

- [x] ~~Download data from zenodo~~ Not in this version yet. In fact, after investigate zenodo's r pacakge available, is probably too complicated to include it in the package :(

- [x] Utilities for data use:
    + [x] daily metrics ( see #1 )
    + [x] filters/getters by metadata
    + [x] helpers (centroid, min/max_time...)

- [x] Tests
    + [x] tests for methods and classes
    + [x] tests for metrics
    + [x] tests for filters/getters
    + [x] tests for helpers

- [x] Documentation
    + [x] functions
    + [x] vignettes
          - [x] quick guide done, not so quick though :(
          - [x] sfn_data & sfn_data_multi classes
          - [x] custom aggregation
          - [x] data flags

- [x] Migrate from sapfluxnetQC1
    + [x] aliases for get methods (these will change in `sapfluxnetr`)
    + [x] regenerate all SfnDatas in sfn_datas (code for it is prepared)
