### ISSUE TITLE
Cleaning task list

### ISSUE THREAD

**Issue by MalditoBarbudo** [sapfluxnet/sapfluxnetr#3]
- [x] Better metadata variable dictionary
- [x] ~~Naming confilcts (md for midday but also for metadata)~~ The context is different so maybe there is no need to declare a different name for midday metrics
- [x] Refactor metadata cache functions (naming inconsistencies)
- [x] Check all functionality works as intended in an integrated framework (this will be done in the big_test script, implemented but waiting for more sites)
- [x] Create a definitive folder for data in server to retrieve the LVL2_passed sites
- [x] Centroid calculation cleaning (Makes no sense return the centroids for env vars also)
- [x] ~~Add normalized_centroid metric to sapf metrics~~ Not possible at the moment. In the future if we
      see it is an indispensable metric it can be implemented

- [x] ... (TBD)

**Comment by MalditoBarbudo** [comment]
Now in server `/data` folder there is a new folder called `sapfluxnet_db` where all versions of sapfluxnet database will be stored. For now the first one will be `0.0.1`
